name: Validate Gradle Wrapper
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  validation:
    name: Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      # We do a run of the new task `templateExample` created by the plugin
      - name: Run the plugin
        run: ./gradlew generateSchemaspyDocs
        if: success()
        # And we verify that the output of the file is correct.
      - name: "Check file existence"
        uses: andstor/file-existence-action@v3
        with:
          files: "./example/build/schemaspy/sakila/index.html"
